name: Deploy to GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google
      id: 'auth'
      uses: 'google-github-actions/auth@v0.8.1'
      with:
        workload_identity_provider: 'projects/552671331836/locations/global/workloadIdentityPools/github-actions-pool/*'
        service_account: 'github-actions-service-account@martin-project-4mlr.iam.gserviceaccount.com'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Create type definitions
      run: yarn tsc
    - name: Build artifacts
      run: yarn build
    - name: Build the Docker image
      run: docker image build . -f packages/backend/Dockerfile --tag backstage
    - name: Docker login to Artifact registry
      uses: 'docker/login-action@v1'
      with:
        registry: 'europe-north1-docker.pkg.dev' # or REGION-docker.pkg.dev
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
