name: Deploy to GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IDENTITY_PROVIDER: 'projects/552671331836/locations/global/workloadIdentityPools/github-actions-identity-pool-3/providers/github-actions-poolprovider'
  SERVICE_ACCOUNT: 'github-actions-service-account@martin-project-4mlr.iam.gserviceaccount.com'
  PROJECT_ID: martin-project-4mlr
  DEPLOYMENT_NAME: backstage
  IMAGE: backstage
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google
        id: 'auth'
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create type definitions
        run: yarn tsc

      - name: Build artifacts
        run: yarn build

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./packages/backend/Dockerfile
          build-args: |
            binary_name=backstage
          push: ${{ GitHub.ref == 'refs/heads/main' }}
          tags: "europe-north1-docker.pkg.dev/$PROJECT_ID/martin-project-repo/$IMAGE:$TAG"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v4.5.7/kustomize_4.5.7_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=europe-north1-docker.pkg.dev/$PROJECT_ID/martin-project-repo/$IMAGE:$TAG
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
