name: Deploy to GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google
        id: 'auth'
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          workload_identity_provider: 'projects/552671331836/locations/global/workloadIdentityPools/github-actions-identity-pool-3/providers/github-actions-poolprovider'
          service_account: 'github-actions-service-account@martin-project-4mlr.iam.gserviceaccount.com'
          create_credentials_file: true
      - run: gcloud auth configure-docker europe-docker.pkg.dev
      - name: Build and Push OCI
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          build-args: |
            binary_name=backstage
          push: ${{ GitHub.ref == 'refs/heads/main' }}
          tags: europe-docker.pkg.dev/martin-project/backstage/backstage:latest
